[Icon Theme]
Name=silvertrim
Description=An accompanying icon theme to the silvertrim Plasma theme.
Example=folder
Directories=scalable/actions,scalable/apps,scalable/places,scalable/mimetypes,scalable/categories,scalable/devices,scalable/status,scalable/emblems,scalable/preferences
Inherits=breeze-dark,gnome,hicolor

[scalable/actions]
Size=22
Context=Actions
Type=Fixed

[scalable/apps]
Size=48
Context=Applications
Type=Scalable

[scalable/places]
Size=48
Context=Places
Type=Scalable

[scalable/places]
Size=64
Context=Places
Type=Scalable

[scalable/places]
Size=96
Context=Places
Type=Scalable

[scalable/mimetypes]
Size=48
Context=MimeTypes
Type=Scalable

[scalable/devices]
Size=96
Context=Devices
Type=Scalable

[scalable/categories]
Size=48
Context=Categories
Type=Scalable

[scalable/status]
Size=48
Context=Status
Type=Scalable

[scalable/emblems]
Size=48
Context=Emblems
Type=Scalable

[scalable/preferences]
Size=48
Context=Preferences
Type=Scalable
